export {default as LogoImage} from './Logo.svg'
export {default as HeroImage} from './hero.webp'
export {default as AboutImage} from './about.webp'
export {default as SingersImage} from './singers.webp'
export {default as SliderCardImage} from './sliderCard.svg'
export { default as DjMixerImage } from './djMixer.svg'
export {default as GuitarImage} from './guitar.svg'
export {default as SaxophoneImage} from './saxophone.svg'
export {default as TrumpetImage} from './trumpet.svg'
export {default as AvatarImage} from './avatar.webp'
export {default as QuotesImage} from './quotes.svg'
export {default as FacebookImage} from './facebook.svg'
export {default as MenuIcon} from './menu.svg'